In [7]:
import numpy as np

In [68]:
x = 'raBarbeR'

In [3]:
alle_dingen = 'abcdefghijklmnopqrstuvwxyz '

In [26]:
zeros = np.zeros((4, 4))
y = 'rabe'

for i in range(0, len(x) - 1):
    zeros[y.index(x[i])][y.index(x[i + 1])] += 1
    
print(zeros)

squish = []
for i in zeros:
    squish.append(sum(i))

print(squish)

[[0. 1. 1. 0.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 0. 0.]]
[2.0, 2.0, 2.0, 1.0]


In [65]:
zeros = np.zeros((len(alle_dingen) + 1, len(alle_dingen) + 1))

for i in range(0, len(x) - 1):
    letter = x[i].lower()
    opvolgende_letter = x[i + 1].lower()
    
    if letter in alle_dingen:
        index_letter = alle_dingen.index(letter)
    else:
        index_letter = 28
    
    if opvolgende_letter in alle_dingen:
        index_opvolgende_letter = alle_dingen.index(opvolgende_letter)
    else:
        index_opvolgende_letter = 28
    
    zeros[index_letter][index_opvolgende_letter] += 1
    
    
print(zeros)

[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0.]
 [1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0

In [66]:
squish_horizontaal = []
for i in zeros:
    squish_horizontaal.append(sum(i))
    
reserve_matrix = []
for i in range(0, 28):
    rij = []
    for j in range(0, 28):
        rij.append(zeros[j][i])
    reserve_matrix.append(rij)
    
squish_verticaal = []
for i in zeros:
    squish_verticaal.append(sum(i))

squish = squish_horizontaal + squish_verticaal
print(squish)

[2.0, 2.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 2.0, 2.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]


In [ ]:
import pandas as pd
wine = pd.read_csv('wine_data.csv', names = ["Cultivator", "Alchol", "Malic_Acid", "Ash", "Alcalinity_of_Ash", "Magnesium", "Total_phenols", "Falvanoids", "Nonflavanoid_phenols", "Proanthocyanins", "Color_intensity", "Hue", "OD280", "Proline"])

In [67]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.neural_network import MLPClassifier

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y)
scaler = StandardScaler()
scaler.fit(X_train)
StandardScaler(copy=True, with_mean=True, with_std=True)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
mlp = MLPClassifier(hidden_layer_sizes=(13,13,13),max_iter=500)
mlp.fit(X_train,y_train)
MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(13, 13, 13), learning_rate='constant',
       learning_rate_init=0.001, max_iter=500, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='adam', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)

In [ ]:
predictions = mlp.predict(X_test)
print(confusion_matrix(y_test, predictions))
print(classification_report(y_test,predictions))

In [ ]:
from tensorflow import keras
from tensorflow.keras import layers, utils
import json
import numpy as np
from typing import Tuple

In [ ]:
data = open(str(path))
frame = json.loads(data.read())
return frame

In [ ]:
def train_model(model: keras.Sequential, frame: dict, batch_size: int, epochs: int, vs: float) -> keras.callbacks:
    """
    Train the model using the trainsets created in create_dataset().
    Parameters
    ----------
        model: tensorflow keras model
            the tensorflow keras model that has been made in create_model().
        frame: dict
            dictionary that is used to create the trainsets in create_datasets().
        batch_size: int
            int that determines the batch_size that is used for training the model.
        epochs: int
            int that determines the amount of epochs which is also used for training the model.
        vs: float
            float that determines the validation_split.
    Return
    ------
        history
            The callback where all the training results are saved in. This is used for plotting the training results.
    """
    history = keras.callbacks.History()

    x_train, y_train = create_datasets(frame, 'formatted_pixels', 'happy')
    model.compile(loss=keras.losses.CategoricalCrossentropy(),
                  optimizer=keras.optimizers.Adam(),
                  metrics=["accuracy"])
    model.fit(x_train, y_train, batch_size=batch_size, epochs=epochs, validation_split=vs, callbacks=[history])

    return history

In [ ]:
def evaluate_model(model: keras.Sequential, frame: dict, batch_size: int) -> list:
    """
    Test the model using testsets created in create_datasets.
    Parameters
    ----------
        model: tensorflow keras model
            the tensorflow keras model that has been made in create_model().
        frame: dict
            dictionary that is used to create the testsets in create_datasets().
        batch_size: int
            int that determines the batch_size that is used for evaluating the model.
    Return
    ------
        results
            list of the results of the model after testing it with te testsets.
    """
    x_test, y_test = create_datasets(frame, 'formatted_pixels', 'happy')
    results = model.evaluate(x_test, y_test, batch_size=batch_size)

    return results